// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

namespace Model.Migrations
{
    [DbContext(typeof(ProyectoDbContext))]
    [Migration("20220227164312_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Domain.Categorias", b =>
                {
                    b.Property<int>("idcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("descripcioncategoria")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nombrecategoria")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("idcategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Model.Domain.PermisoCat", b =>
                {
                    b.Property<int>("idpermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idcategoria")
                        .HasColumnType("int");

                    b.Property<int>("idusuariopermitido")
                        .HasColumnType("int");

                    b.HasKey("idpermiso");

                    b.ToTable("PermisoCat");
                });

            modelBuilder.Entity("Model.Domain.Tareas", b =>
                {
                    b.Property<int>("idtarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("archivado")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("estadotarea")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechafin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechainicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("idcategoriatarea")
                        .HasColumnType("int");

                    b.Property<int>("idusuarioasignado")
                        .HasColumnType("int");

                    b.Property<int>("idusuariocreador")
                        .HasColumnType("int");

                    b.Property<int>("idusuariotermino")
                        .HasColumnType("int");

                    b.Property<int>("prioridad")
                        .HasColumnType("int");

                    b.HasKey("idtarea");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Model.Domain.Usuario", b =>
                {
                    b.Property<int>("idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<int>("tipousuario")
                        .HasColumnType("int");

                    b.HasKey("idusuario");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
